import { Prisma } from "@lifeweb/db";

// Excludes bot/UI plumbing that happens to go out as a DM but isn't part of
// a GM<->player conversation: embeds (meta.embed === true), anything tagged
// source: "system_notice" (edit-flow prompts, mention relays, proxy
// hand-back, reaction refusals — see bot/src/lib/dm.js call sites), and
// source: "prompt_reply" (what a player typed back INTO one of those
// prompts). Applied at the query, not the render, so a future noisy sendDm()
// call needs to pass its own `source` to show up here at all.
//
// Written as explicit null-tolerant ORs rather than a NOT over the two
// conditions. In SQL, `NOT (meta->'embed' = true)` is NULL — not true — for
// every row whose meta is NULL or lacks the key, and a NULL predicate drops
// the row. Almost every message is such a row, so the NOT form returned an
// empty thread for every conversation (and a 404 for a player with no
// character, since the page treats "no messages and no character" as an
// unknown id). Same trap on `source`, which is NULL on older rows and on
// anything web/lib/discordGuild.js#sendDm sends without an explicit source.
const NOT_NOISE = [
  { OR: [{ source: null }, { source: { not: "system_notice" } }] },
  // prompt_reply is history now: nothing writes it since ✏️ became a button
  // and a modal (bot/src/lib/editModal.js), so no inbound DM is generated by
  // the edit flow at all. The rows already in the table stay hidden — the
  // pane used to show them, and a GM reading a stray in-character poster as
  // mail is exactly what this filter exists to stop.
  { OR: [{ source: null }, { source: { not: "prompt_reply" } }] },
  {
    OR: [
      { meta: { equals: Prisma.DbNull } },
      { meta: { path: ["embed"], equals: Prisma.DbNull } },
      { meta: { path: ["embed"], not: true } },
    ],
  },
];

export function withoutDmNoise(where) {
  return { ...where, AND: [...(where?.AND ?? []), ...NOT_NOISE] };
}

// The raw-SQL twin of withoutDmNoise, for the $queryRaw call sites that can't
// take a Prisma `where`. Keeping the two in one file is the point: the rail
// badge and the desk disagreed for a week because navItems.js hand-rolled its
// own copy of this predicate and never got the prompt_reply clause.
//
// `alias` is a code-supplied literal (the table alias in the caller's FROM),
// never user input, so Prisma.raw is safe here.
export function dmNoiseSql(alias) {
  const col = (c) => Prisma.raw(alias ? `${alias}."${c}"` : `"${c}"`);
  return Prisma.sql`(${col("source")} IS DISTINCT FROM 'system_notice')
    AND (${col("source")} IS DISTINCT FROM 'prompt_reply')
    AND ((${col("meta")}->>'embed') IS DISTINCT FROM 'true')`;
}
