import fs from "node:fs/promises";
import path from "node:path";
import { prisma, letterPlaqueFile } from "@lifeweb/db";

// Serves a character's profile picture: their uploaded one if they have set
// one, otherwise the letter plaque for the first letter of their FIRST name
// (never the honorific or the GM-granted title).
//
// The default is resolved here, at read time, from the live row — which is
// why renaming a character updates their avatar with no job, no hook and no
// stored bytes. An uploaded avatarData always wins, so this never overwrites
// a picture someone chose.
//
// The plaques are generated by web/scripts/generate-letters.js
// (`npm run assets:letters --workspace=web`) and committed.
//
// Which tile a name maps to is decided by letterPlaqueFile in
// db/lib/presentedIdentity.js, shared with the bot so a forced identity
// ("Beast") points at the same B tile this route would serve.
const LETTERS_DIR = path.join(process.cwd(), "public/assets/letters");
const plateCache = new Map();

function readPlate(file) {
  if (!plateCache.has(file)) {
    // Cache the promise, not the buffer, so concurrent requests for the same
    // letter share one read.
    plateCache.set(
      file,
      fs.readFile(path.join(LETTERS_DIR, file)).catch((err) => {
        plateCache.delete(file);
        throw err;
      }),
    );
  }
  return plateCache.get(file);
}

export async function GET(_request, { params }) {
  const { characterId } = await params;

  const character = await prisma.character.findUnique({
    where: { id: characterId },
    select: { avatarData: true, avatarMimeType: true, firstName: true },
  });

  if (!character) {
    return new Response("Not found", { status: 404 });
  }

  let data = character.avatarData;
  let contentType = character.avatarMimeType ?? "application/octet-stream";

  if (!data) {
    try {
      data = await readPlate(letterPlaqueFile(character.firstName));
      contentType = "image/webp";
    } catch (err) {
      console.error(`Missing letter plaque for character ${characterId}:`, err);
      return new Response("Not found", { status: 404 });
    }
  }

  return new Response(data, {
    headers: {
      "Content-Type": contentType,
      // Safe despite being derived from a mutable row: every caller appends
      // ?v=<updatedAt ms>, which any character write bumps.
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
